### ISSUE TITLE
Move group dies when launching Denso Robot bringup

### ISSUE THREAD

**Issue by AniketCOAST** [DENSORobot/denso_robot_ros2#9]
**Ubuntu version:** 22.04 LTS
**ROS2 version:** Humble
**DDS version:** FastDDS was used because CycloneDDS, although recommended by MoveIt2, was giving a problem where the launch file could not contact the controller_manager

Hello,

I am having an issue when running the **** launch file for enabling SlaveMode control for my Robotic Arm VS087.

**Issue:** 

The MoveGroupInterface is dying because of joint_limits.yaml file. Because of this the **get_planning_scene** service does not get called. Because of this, even though the denso_robot_bringup launch file will get launched, I am not able to move the robot through the SlaveMode. For example, the **denso_robot_moveit_pickandplace** launch file does nothing after it has been launched alongside the denso_robot_bringup launch file.

I identified that the joint_limits.yaml file was the issue because it said the following things in the output:
```
[move_group-3] terminate called after throwing an instance of 'rclcpp::exceptions::RCLInvalidROSArgsError'
[move_group-3]   what():  failed to initialize rcl: Couldn't parse params file: '--params-file /home/Administrator/workspace/denso_ros2_ws/install/denso_robot_moveit_config/share/denso_robot_moveit_config/robots/vs087a4_w7n_nnn/config/joint_limits.yaml'. Error: Cannot have a value before ros__parameters at line 3, at ./src/parse.c:793, at ./src/rcl/arguments.c:406
```

Here is the entire output:
[denos_robot_bringup_launch_fastdds_outout.txt](https://github.com/user-attachments/files/19636877/denos_robot_bringup_launch_fastdds_outout.txt)

Here is the joint_limits.yaml file that I am using:
```
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 2.9845130209103
    has_acceleration_limits: true
    max_acceleration: 10.8341138784623
  joint_2:
    has_velocity_limits: true
    max_velocity: 2.73580360250111
    has_acceleration_limits: true
    max_acceleration: 9.21882910903405
  joint_3:
    has_velocity_limits: true
    max_velocity: 3.28296432300133
    has_acceleration_limits: true
    max_acceleration: 10.4220852752977
  joint_4:
    has_velocity_limits: true
    max_velocity: 4.10370540375167
    has_acceleration_limits: true
    max_acceleration: 11.2448160313953
  joint_5:
    has_velocity_limits: true
    max_velocity: 4.10370540375167
    has_acceleration_limits: true
    max_acceleration: 10.5834147847058
  joint_6:
    has_velocity_limits: true
    max_velocity: 6.56592864600267
    has_acceleration_limits: true
    max_acceleration: 13.3349699837062
```

**Steps to replicate:**

1. Source ROS2 with `source /opt/ros/humble/setup.bash`
2. Source the denos ros2 robot workspace by executing `source install/setup.bash` inside the workspace
3. Run `ros2 launch denso_robot_bringup denso_robot_bringup.launch.py model:=vs087a4_w7n_nnn sim:=false ip_address:=192.168.X.A send_format:=256 recv_format:=258` to enable b-Cap SlaveMode
4. Run `ros2 launch denso_robot_moveit_demo denso_robot_moveit_pickandplace.launch.py model:=vs087a4_w7n_nnn scale_factor:=0.05 num_cycles:=1` to move the robot with the pick and place demo

**Expected result:**

The robot will move according to the parameters set.

**Actual result:**

The Robot does not move. In the output for the denso ros2 robot bringup, I can see the output messages about MoveGroup dying. In Rviz, I get the following warning as expected:

![Image](https://github.com/user-attachments/assets/3240d335-251d-4f45-93b0-db3c4f4b650a)

**Comment by furukawahiromi** [comment]
Hello @AniketCOAST -san,

AcquireVelAcc only supports MoveIt.
Please refer to the joint_limits.yaml that we have attached and modify the joint_limits.yaml to the MoveIt2 format:

```
move_group:
  ros__parameters:
    robot_description_planning:
      joint_limits:
        joint_1:
          has_velocity_limits: true
          max_velocity: 0.3
          ...
          (snip)
```

We hope it will be resolved.

Best regards,
furukawa
